spring:
  datasource:
    sql-script-encoding: UTF-8
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    url: jdbc:h2:file:./database/testdb
    username: sa
    password:
    initialize: true


  jpa:
    hibernate:
      ddl-auto: update

# AOP
#spring.jpa.generate-ddl
#spring.aop.auto=true # Add @EnableAspectJAutoProxy.
#spring.aop.proxy-target-class=false # Whether subclass-based (CGLIB) proxies are to be created (true) as opposed to standard Java interface-based proxies (false).

  aop:
    auto: true

security:
  basic:
    enabled: false

